/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,  useEffect } from 'react'

import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'
import { Text } from '@react-three/drei'
import { Vector3 } from 'three'
import { useStore } from '../../../Hooks/useStore'

export default function Model(props) {
  const [playerPosition , visitLink,
    setVisitLink,stopEveryMovement]  = useStore((state)=>[state.playerPosition,
      state.visitLink,state.setVisitLink,state.stopEveryMovement]);
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Chess.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.BoardAction.reset().fadeIn(0.1).play();
    actions.LightAction.reset().fadeIn(0.1).play();
    actions.PropellerAction.reset().fadeIn(0.1).play();
    return () => {
      actions.BoardAction.fadeOut(0.5);
      actions.LightAction.fadeOut(0.5);
      actions.PropellerAction.fadeOut(0.5);
    }
  },[actions.BoardAction, actions.LightAction, actions.PropellerAction] )
  useEffect(()=>{
    const handleKeyPress = (e)=>{
      if(e.code==="Enter" && !visitLink){
        
        setVisitLink(true);
      } 
    }
    window.addEventListener('keypress',handleKeyPress);
    return ()=>{
      window.removeEventListener('keypress',handleKeyPress);
    }
  })
  useEffect(() => {
    const playerVector = new Vector3(playerPosition[0],playerPosition[1],playerPosition[2]);
    const ufoVector = new Vector3(props.position[0],props.position[1],props.position[2]);
    const distance = playerVector.distanceTo(ufoVector);
    
    if(visitLink && distance<=6 ){
        window.open(props.url);       
        stopEveryMovement();
        setVisitLink(false);
    }
  },[playerPosition,props.position, props.url, setVisitLink, stopEveryMovement, visitLink])
  return (
    <group ref={group} {...props} dispose={null}>
      <Text color={'hotpink'}
      castShadow
      fontSize={1}
      rotation={[-Math.PI/3,0,0]}
      lineHeight={1}
       > Multiplayer Chess</Text>
       <Text color={'skyblue'}
      castShadow
      fontSize={0.8}
      maxWidth={15}
      rotation={[-Math.PI/3,0,0]}
      position={[0,-2.5,0]}
      lineHeight={1}
       > A multiplayer chess game created with React and Firebase </Text>
      <group name="Light" position={[0.01, 8.49, -0.41]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={5} distance={10} decay={2} color="#0f3aff" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group name="Board" position={[0, 8.43, -1.12]}>
        <mesh material={materials.Body} geometry={nodes.Cube002.geometry} />
        <mesh material={materials.Screen} geometry={nodes.Cube002_1.geometry} />
        <mesh material={materials.HoloGram} geometry={nodes.Cube002_2.geometry} />
        <mesh material={materials.Pipe} geometry={nodes.Cube002_3.geometry} />
      </group>
      <mesh name="Fan" material={materials.Propeller} geometry={nodes.Fan.geometry} position={[0, 8.43, -1.12]} />
    </group>
  )
}

useGLTF.preload('/Chess.glb')
