/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function AboutMe(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/AboutMe.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <pointLight intensity={2} distance={15} position={[0,0,0]} />
      <group position={[0, 0.2, 0]}>
        <mesh castShadow material={materials.Arrow} scale={[1,0.5,2.5]} geometry={nodes.Cube_1.geometry} />
        <mesh castShadow material={materials.ArrowGlow} scale={[1,0.5,2.5]}  geometry={nodes.Cube_2.geometry} />
      </group>
      <mesh
        material={materials.TextGlow}
        geometry={nodes.Text.geometry}
        position={[0.09, 0.33, -0.2]}
        rotation={[0, 1.57, 0]}
      />
    </group>
  )
}

useGLTF.preload('/AboutMe.glb')
