/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {  useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { PositionalAudio } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/CenterPose.glb')
  const ref = useRef();
  useFrame(()=>{
    
    if(ref.current && ref.current.context.state!=='running'){
      ref.current.context.resume();
    }
  })
  
  return (
    <group ref={group} {...props} dispose={null}>
      <PositionalAudio ref={ref} distance={2}  url='AudioAssets/IndianTheme.mp3'/>
      <pointLight intensity={5} distance={20} position={[-5,40,3]} />
      <pointLight intensity={2.5} color={'coral'} distance={20} position={[5,30,5]} />
      <group position={[0.04, 5.52, 0.34]}>
        <mesh material={nodes.Body.material} geometry={nodes.Body.geometry} position={[-0.04, 24.09, -7]} />
      </group>
      <mesh
        material={materials.Material}
        geometry={nodes.Pole.geometry}
        position={[6.37, 26.37, 9.62]}
        rotation={[0, 0, -0.56]}
      />
      <mesh
        material={materials.Flag}
        geometry={nodes.Flag.geometry}
        position={[14.2, 26.98, 9.62]}
        rotation={[Math.PI / 2, -0.56, 0]}
      />
    </group>
  )
}

useGLTF.preload('/CenterPose.glb')
