/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useRef,  useEffect } from 'react'

import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'
import { Text } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/NameCharacter.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions.GreenAction.reset().play();
    actions.PurpleAction.reset().play();
    return ()=>{
      actions.GreenAction.fadeOut(1);
      actions.PurpleAction.fadeOut(1);
    }
  },[actions.GreenAction,actions.PurpleAction])
  return (
    <group ref={group} {...props} dispose={null}>
      <Text color={'hotpink'}
        castShadow
        fontSize={0.5}
        rotation={[0,0,0]}
        position={[5,5,0]}
        lineHeight={1}
        maxWidth={5}
      letterSpacing={0.02}
      textAlign={'center'}
       > Hey Guys, Welcome to my small world !!!   I am Kaushal , 
       An aspiring Web Developer. You can roam as much as you want here, NO TAX SHALL BE LEVIED !
        </Text>
      <group name="Purple" position={[-6.76, 15.56, 0.34]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={100} distance={10} decay={2} color="#ff17ba" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group name="Green" position={[7.39, 15.56, 0.34]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={100} distance={10} decay={2} color="#00ff00" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh
        material={materials['Material.001']}
        geometry={nodes.Name.geometry}
        position={[0, 13.47, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[3.16, 3.16, 3.16]}
      />
      <group position={[0, 11.47, -0.08]}>
        <mesh material={materials.Back} geometry={nodes.Cube.geometry} />
        <mesh material={materials.Front} geometry={nodes.Cube_1.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/NameCharacter.glb')
